apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: gary-cse644
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
    - job_name: 'gary-python-web'
      metrics_path: /metrics
      static_configs:
      - targets: ['python-web.gary-cse644.svc.cluster.local:8888']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: gary-cse644
spec:
  replicas: 1
  selector:
    matchLabels: {app: prometheus}
  template:
    metadata:
      labels: {app: prometheus}
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.54.1
        args: ['--config.file=/etc/prometheus/prometheus.yml']
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap: {name: prometheus-config}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: gary-cse644
spec:
  selector: {app: prometheus}
  ports:
  - port: 9090
    targetPort: 9090
