apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gary-cse644-a03
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zongyifang-ux/CSE644-Assignment-03.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gary-cse644
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
